#!/bin/sh

MAIN="/usr/bin/exquisite -verbose"
WRITE="/usr/bin/exquisite_write"

# Start Exquisite with the basic theme def.
$MAIN -t /usr/share/efl-themes/bootsplash/default.edj -x 640 -y 480 &
#$MAIN -t /usr/share/efl-themes/bootsplash/default.edj -x 1280 -y 1024 &

# Run the simple core test...
$WRITE "TITLE Welcome to Bootsplash"
sleep 1
$WRITE "MSG Progress Bar Test"
for i in 0 10 20 30 40 50 60 70 80 90 100 ; do
    $WRITE "PROGRESS $i"
    millisleep 100
done
sleep 2
$WRITE "MSG Shutting down..."
sleep 3
$WRITE "QUIT"
